name: data-review-test
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4=4.12.3
  - jupyterlab=4.2.5
  - jupyterlab-plotly-extension=1.0.0
  - matplotlib=3.7.0
  - matplotlib-base=3.7.0
  - matplotlib-inline=0.1.6
  - matplotlib-venn=1.1.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openpyxl=3.1.5
  - pandas=2.2.3
  - pillow=11.0.0
  - pip=24.2
  - plotly=5.24.1
  - prince=0.13.0
  - python=3.10.16
  - pyyaml=6.0.2
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - seaborn=0.13.2
  - pip:
      - pyarrow==18.1.0
      - streamlit==1.41.1
      - watchdog==6.0.0
